### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by corey-mitchell** [corey-mitchell/webScraper#1]
(node:14148) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (C:\Users\Macaroni Biff\Desktop\code\Class-Assignments\webScraper\node_modules\express\lib\response.js:767:10)
    at ServerResponse.json (C:\Users\Macaroni Biff\Desktop\code\Class-Assignments\webScraper\node_modules\express\lib\response.js:264:10)
    at db.Article.create.then.catch (C:\Users\Macaroni Biff\Desktop\code\Class-Assignments\webScraper\server.js:82:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by corey-mitchell** [comment]
Receiving this error for every article from the scraper. Need to do some studying.

**Comment by corey-mitchell** [comment]
When I deleted the .catch() from line 81 from server.js it gave me another error which told me the true problem. Which was that line 64 was targeting ```result.url``` when my model name was 'link'. So changing ```result.url``` to ```result.link``` fixed the issue. I then added the .catch back to line 81 and everything still works!
